apiVersion: v2
name: komodo
description: Komodo Core with MongoDB
version: 0.1.0
appVersion: "2.2.0"
type: application
keywords:
  - komodo
  - mongodb
  - devops
home: https://komo.do/
icon: https://raw.githubusercontent.com/moghtech/komodo/main/ui/public/apple-touch-icon.png
sources:
  - https://github.com/moghtech/komodo
maintainers:
  - name: antiantiops
