{{- if not .Values.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "komodo.secretName" . }}
  labels:
    {{- include "komodo.labels" . | nindent 4 }}
type: Opaque
stringData:
  mongo-root-password: {{ required "mongo.auth.rootPassword is required when existingSecret.name is empty" .Values.mongo.auth.rootPassword | quote }}
  komodo-init-admin-password: {{ required "komodo.auth.initAdminPassword is required when existingSecret.name is empty" .Values.komodo.auth.initAdminPassword | quote }}
  komodo-jwt-secret: {{ required "komodo.auth.jwtSecret is required when existingSecret.name is empty" .Values.komodo.auth.jwtSecret | quote }}
  komodo-passkey: {{ required "komodo.auth.passkey is required when existingSecret.name is empty" .Values.komodo.auth.passkey | quote }}
  komodo-webhook-secret: {{ required "komodo.auth.webhookSecret is required when existingSecret.name is empty" .Values.komodo.auth.webhookSecret | quote }}
{{- end }}
